#!/usr/bin/perl
use strict;
use warnings;

use File::Copy;

use Getopt::Long;

use lib $ENV{GL_LIBDIR};
use Gitolite::Rc;
use Gitolite::Common;

$|++;

# best called via 'gitolite trigger POST_COMPILE'; other modes at your own
# risk, especially if the rc file specifies arguments for it.  (That is also
# why it doesn't respond to "-h" like most gitolite commands do).
#
my $uid = getpwnam("git");
my $gid = getgrnam("apache");

my $authzfn = "svn.authz";

my $ab = $rc{GL_ADMIN_BASE};
my $ab_authzfile = "$ab/conf/" . $authzfn;
trace( 1, "'$ab_authzfile' not found in '$ab'; exiting" ), exit if not -f $ab_authzfile;
my $authzfile = "/home/svn/conf/authz";

# ----------------------------------------------------------------------
trace( 1, "copy '$ab_authzfile' to '$authzfile'" );
copy($ab_authzfile, $authzfile) or exit 0;
chmod 0640, $authzfile;
chown $uid, $gid, $authzfile;