#!/usr/bin/perl
use strict;
use warnings;

use File::Copy;

use Getopt::Long;

use lib $ENV{GL_LIBDIR};
use Gitolite::Rc;
use Gitolite::Common;

$|++;

# best called via 'gitolite trigger POST_COMPILE'; other modes at your own
# risk, especially if the rc file specifies arguments for it.  (That is also
# why it doesn't respond to "-h" like most gitolite commands do).
#
my $uid = getpwnam("git");
my $gid = getgrnam("apache");

my $htpfn = "git.passwd";

my $ab = $rc{GL_ADMIN_BASE};
my $ab_htpfile = "$ab/keydir/" . $htpfn;
trace( 1, "'$ab_htpfile' not found in '$ab'; exiting" ), exit if not -f $ab_htpfile;
my $htpfile       = "$ENV{HOME}/" . $htpfn;

# ----------------------------------------------------------------------
trace( 1, "copy '$ab_htpfile' to '$htpfile'" );
copy($ab_htpfile, $htpfile) or exit 0;
chmod 0640, $htpfile;
chown $uid, $gid, $htpfile;